<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/normalize.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/style.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/slide.min.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/animate.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/jquery.fancybox.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/range.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('css/jquery.timepicker.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('add/alert/main.css') }}" >
<link rel="stylesheet" type="text/css" href="{{ URL::asset('add/jquery-ui-1.10.4.custom.min.css') }}" >
